Repository jamesbeamie/LG-api, pull requests merged in 2020-04, with the labels that each got.

#6 feat-172047885 Oauth2
  Routes/authentication/login/Login.js
  Routes/authentication/registration/User.js
  Routes/authentication/socialAuth/GoogleAuth.js
  middlewares/PassportConfig.js
  models/authModels/UserModel.js
  models/authModels/socialAuthModel/googleAuthModel.js
  package.json
  server.js
Labels: TO-REVISIT

#7 feat-172048210 Create article
  Routes/Articles/Articles.js
  middlewares/ImageUploader.js
  models/ArticleModels/Article.js
  package.json
  server.js
  uploads/Screen Shot 2019-11-21 at 10.38.21 AM.png
Labels: COMPLETED, IN REVIEW, READY FOR MERGE

#8 feat-#172048375 Get all articles
  Routes/Articles/Articles.js
Labels: COMPLETED, READY FOR MERGE

#9 feat-#172048902 Delete article
  Routes/Articles/Articles.js
Labels: COMPLETED, READY FOR MERGE, merged

#10 feat-#172048722 Update an article
  Routes/Articles/Articles.js
Labels: COMPLETED, READY FOR MERGE, merged

#11 feat-#72049574 Like or dislike an article
  Routes/Articles/Articles.js
  Routes/Dislikes/Dislikes.js
  Routes/Likes/Likes.js
  Routes/authentication/registration/User.js
  models/ArticleModels/Article.js
  models/DislikeModal/DisLikeModel.js
  models/LikesModel/LikeModel.js
  models/authModels/UserModel.js
  server.js
Labels: COMPLETED, READY FOR MERGE, merged

#12 feat-172150288 Create a comment for an article
  Routes/Articles/Articles.js
  Routes/Dislikes/Dislikes.js
  Routes/Likes/Likes.js
  Routes/comments/Comments.js
  models/ArticleModels/Article.js
  models/commentsModel/CommentsModel.js
  server.js
Labels: COMPLETED, READY FOR MERGE

#14 feat-172150489 Delete a comment
  Routes/comments/Comments.js
Labels: COMPLETED, TO-REVISIT, merged

#15 feat-172047922 Password reset
  Routes/authentication/passwordReset/PasswordReset.js
  middlewares/NodeMailer.js
  models/authModels/UserModel.js
  package.json
  server.js
Labels: COMPLETED, READY FOR MERGE, merged

#16 #172050160: set up Tests Using Jest
  Routes/Articles/tests/Articles.spec.js
  package.json
  server.js
Labels: READY FOR REVIEW

#19 chore-172393890 Create Route handlers
  RouteHandlers/ArticleHandlers/articleHandlers.js
  RouteHandlers/authHandlers/LoginHandler.js
  RouteHandlers/authHandlers/SingUpHandler.js
  RouteHandlers/authHandlers/pwdResetHandler.js
  RouteHandlers/commentsHandlers/commentsHandler.js
  RouteHandlers/dislikesHandlers/dislikeHandler.js
  RouteHandlers/likesHandlers/likesHandler.js
  Routes/Articles/Articles.js
  Routes/Dislikes/Dislikes.js
  Routes/Likes/Likes.js
  Routes/authentication/login/Login.js
  Routes/authentication/passwordReset/PasswordReset.js
  Routes/authentication/registration/User.js
  Routes/comments/Comments.js
Labels: COMPLETED, READY FOR MERGE, merged

#20 chore-172396103 Assemble routes in one folder and version the API
  Routes/Articles/Articles.js
  Routes/Articles/tests/Articles.spec.js
  Routes/Dislikes/Dislikes.js
  Routes/Likes/Likes.js
  Routes/authentication/login/Login.js
  Routes/authentication/passwordReset/PasswordReset.js
  Routes/authentication/registration/User.js
  Routes/authentication/socialAuth/GoogleAuth.js
  Routes/comments/Comments.js
  Routes/index.js
  server.js
  tests/article_tests/ArticlesHandlers.spec.js
Labels: COMPLETED, READY FOR MERGE, Reviewed, merged

#18 chore-172393750 Set Up Tests for articles
  RouteHandlers/ArticleHandlers/articleHandlers.js
  tests/article_tests/ArticleRoutes.spec.js
  tests/article_tests/ArticlesHandlers.spec.js
Labels: COMPLETED
